### ISSUE TITLE
add proposed "gallery" examples

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/binder-notebook#2]
Add examples proposed in https://github.com/MDAnalysis/MDAnalysis.github.io/issues/4 to the binder-notebook repository.

Suggestions
- [ ] [Simple RMSF b-factor coloring with MDAnalysis](https://gist.github.com/orbeckst/6bea4a4be3ad0eb541e105edd58e93bf)
- [ ] SciPy paper examples
- [ ] stuff from [MDAnalysis/MDAnalysisCookbook](https://github.com/MDAnalysis/MDAnalysisCookbook) (see issue https://github.com/MDAnalysis/MDAnalysisCookbook/issues/4)
- [ ] HOLE (see PR #1 )
- [ ] @philipwfowler 's lipid analysis https://github.com/MDAnalysis/MDAnalysis.github.io/issues/4#issuecomment-149800857
- [ ] polymer things e.g. @richardjgowers 's  [persistence length tutorial](https://github.com/richardjgowers/persistence_length_tutorial/blob/master/tutorial.ipynb)
- [ ] [PSA Tutorial](https://github.com/Becksteinlab/PSAnalysisTutorial) 
- [ ] [Flows](http://sbcb.bioch.ox.ac.uk/flows/) and streamlines
